import type {
  SpacemanColorId,
  SpacemanColorOption,
  SpacemanHatId,
  SpacemanHatOption,
  SpacemanPetId,
  SpacemanPetOption,
} from "../types/customization.types";

export const SPACEMAN_COLOR_OPTIONS = [
  {
    id: "original",
    label: "Original issue",
    shortLabel: "Original",
    modelColor: null,
    swatch: "linear-gradient(135deg, #f46bad 0 48%, #dff7fb 52% 100%)",
  },
  {
    id: "mars-red",
    label: "Mars red",
    shortLabel: "Mars",
    modelColor: "#ef4655",
    swatch: "#ef4655",
  },
  {
    id: "solar-orange",
    label: "Solar orange",
    shortLabel: "Solar",
    modelColor: "#f58a3c",
    swatch: "#f58a3c",
  },
  {
    id: "signal-yellow",
    label: "Signal yellow",
    shortLabel: "Signal",
    modelColor: "#f1cb4b",
    swatch: "#f1cb4b",
  },
  {
    id: "bio-lime",
    label: "Bio lime",
    shortLabel: "Bio",
    modelColor: "#72d66a",
    swatch: "#72d66a",
  },
  {
    id: "orbit-teal",
    label: "Orbit teal",
    shortLabel: "Orbit",
    modelColor: "#2bbba8",
    swatch: "#2bbba8",
  },
  {
    id: "ion-cyan",
    label: "Ion cyan",
    shortLabel: "Ion",
    modelColor: "#45c8e6",
    swatch: "#45c8e6",
  },
  {
    id: "deep-blue",
    label: "Deep blue",
    shortLabel: "Deep",
    modelColor: "#5479e6",
    swatch: "#5479e6",
  },
  {
    id: "nebula-violet",
    label: "Nebula violet",
    shortLabel: "Nebula",
    modelColor: "#9465d8",
    swatch: "#9465d8",
  },
  {
    id: "nova-pink",
    label: "Nova pink",
    shortLabel: "Nova",
    modelColor: "#d957a0",
    swatch: "#d957a0",
  },
  {
    id: "lunar-white",
    label: "Lunar white",
    shortLabel: "Lunar",
    modelColor: "#e7eff0",
    swatch: "#e7eff0",
  },
  {
    id: "graphite",
    label: "Graphite",
    shortLabel: "Graphite",
    modelColor: "#4d5965",
    swatch: "#4d5965",
  },
] as const satisfies readonly SpacemanColorOption[];

export const getSpacemanColorOption = (
  colorId: SpacemanColorId
): SpacemanColorOption => {
  return (
    SPACEMAN_COLOR_OPTIONS.find((option) => option.id === colorId) ??
    SPACEMAN_COLOR_OPTIONS[0]
  );
};

export const resolveSpacemanSuitColor = (
  colorId: SpacemanColorId
): string | undefined => {
  return getSpacemanColorOption(colorId).modelColor ?? undefined;
};

export const SPACEMAN_HAT_OPTIONS = [
  {
    id: "none",
    label: "Standard helmet",
    shortLabel: "No hat",
    description: "Original academy helmet profile.",
    modelUrl: null,
    accent: "#7fddeb",
    targetWidth: 0,
    maxHeight: 0,
    contactY: 0,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
  },
  {
    id: "arcane",
    label: "Arcane navigator",
    shortLabel: "Arcane",
    description: "A compact enchanted flight cap.",
    modelUrl: "/models/hats/arcane-hat.glb",
    accent: "#9b74df",
    targetWidth: 2.8,
    maxHeight: 1.85,
    contactY: 1.42,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.02,
  },
  {
    id: "cowboy",
    label: "Frontier ranger",
    shortLabel: "Ranger",
    description: "Wide brim for distant orbital frontiers.",
    modelUrl: "/models/hats/cowboy-hat.glb",
    accent: "#d69455",
    targetWidth: 3.35,
    maxHeight: 1.55,
    contactY: 1.4,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.04,
    centerBias: [0, 0.04],
  },
  {
    id: "samurai",
    label: "Neo ronin",
    shortLabel: "Ronin",
    description: "Low-profile tactical samurai shell.",
    modelUrl: "/models/hats/samurai-hat.glb",
    accent: "#ef5f69",
    targetWidth: 3.1,
    maxHeight: 1.2,
    contactY: 1.41,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.1,
  },
  {
    id: "crew",
    label: "Galley crew cap",
    shortLabel: "Crew",
    description: "Tall service cap from the academy galley.",
    modelUrl: "/models/hats/crew-hat.glb",
    accent: "#5cc8e6",
    targetWidth: 3.15,
    maxHeight: 1.95,
    contactY: 1.42,
    rotation: [0, 0, 0],
    offset: [0, 0, 0.5],
    shapeScale: [1, 0.4, 0.72],
    seatRatio: 0.02,
  },
  {
    id: "captain",
    label: "Lich captain",
    shortLabel: "Captain",
    description: "Command headgear recovered from a ghost fleet.",
    modelUrl: "/models/hats/captain-hat.glb",
    accent: "#b0c5df",
    targetWidth: 3.05,
    maxHeight: 1.75,
    contactY: 1.42,
    rotation: [0, 0, 0],
    offset: [0.03, 0, 0],
    seatRatio: 0.04,
  },
  {
    id: "miner",
    label: "Deep-core miner",
    shortLabel: "Miner",
    description: "Reinforced lamp helmet for dark asteroid shafts.",
    modelUrl: "/models/hats/miner-hat.glb",
    accent: "#f2c34e",
    targetWidth: 2.7,
    maxHeight: 1.18,
    contactY: 1.4,
    rotation: [0, -Math.PI / 2, 0],
    offset: [0, 0, 0],
    seatRatio: 0.035,
  },
  {
    id: "viking",
    label: "Void viking",
    shortLabel: "Viking",
    description: "Horned armor balanced for zero gravity.",
    modelUrl: "/models/hats/viking-hat.glb",
    accent: "#76a9cc",
    targetWidth: 2.92,
    maxHeight: 1.38,
    contactY: 1.53,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    shapeScale: [1.12, 0.8, 1],
    partScales: [
      {
        name: "Object_4",
        scale: [1.22, 1, 1.08],
      },
    ],
    seatRatio: 0.08,
    centerBias: [0, 0.14],
  },
  {
    id: "crown",
    label: "Solar crown",
    shortLabel: "Crown",
    description: "A ceremonial crown for academy champions.",
    modelUrl: "/models/hats/crown.glb",
    accent: "#efc651",
    targetWidth: 1.55,
    maxHeight: 1,
    contactY: 1.42,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.02,
  },
  {
    id: "witch",
    label: "Nebula witch",
    shortLabel: "Witch",
    description: "A broad spectral hat tuned to nebula currents.",
    modelUrl: "/models/hats/witch-hat.glb",
    accent: "#a866df",
    targetWidth: 2.9,
    maxHeight: 1.76,
    contactY: 1.64,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.045,
    centerBias: [0, 0.12],
  },
  {
    id: "top-hat",
    label: "Orbital formal",
    shortLabel: "Top hat",
    description: "Formal command wear for academy ceremonies.",
    modelUrl: "/models/hats/top-hat.glb",
    accent: "#c6d8e1",
    targetWidth: 2.45,
    maxHeight: 1.42,
    contactY: 1.66,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    seatRatio: 0.035,
    centerBias: [0, 0.12],
  },
] as const satisfies readonly SpacemanHatOption[];

export const getSpacemanHatOption = (
  hatId: SpacemanHatId
): SpacemanHatOption => {
  return (
    SPACEMAN_HAT_OPTIONS.find((option) => option.id === hatId) ??
    SPACEMAN_HAT_OPTIONS[0]
  );
};

export const SPACEMAN_PET_PACK_URL = new URL(
  "../../New Model/Pet/roblox_pet_pack_low_poly_3.glb",
  import.meta.url
).href;

export const SPACEMAN_ANIMATED_PET_URLS = {
  chick: new URL(
    "../../New Model/Pet/animated_chick.glb",
    import.meta.url
  ).href,
  frog: new URL("../../New Model/Pet/frog.glb", import.meta.url).href,
  emberElement: new URL(
    "../../New Model/Pet/model.ember_element.glb",
    import.meta.url
  ).href,
  pou: new URL("../../New Model/Pet/pou.glb", import.meta.url).href,
  wyvern: new URL("../../New Model/Pet/wyvern.glb", import.meta.url).href,
} as const;

export const SPACEMAN_PET_OPTIONS = [
  {
    id: "none",
    label: "Solo deployment",
    shortLabel: "No pet",
    description: "Continue the mission without a companion link.",
    modelUrl: null,
    sourceNodeName: null,
    icon: "none",
    rarity: "STANDARD",
    accent: "#85a7b0",
    targetHeight: 0,
    targetFootprint: 0,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
  },
  {
    id: "solar-chick",
    label: "Solar chick",
    shortLabel: "Chick",
    description: "An energetic academy hatchling with a full-body idle loop.",
    modelUrl: SPACEMAN_ANIMATED_PET_URLS.chick,
    sourceNodeName: null,
    icon: "chick",
    rarity: "COMMON",
    accent: "#f6d35d",
    targetHeight: 1.5,
    targetFootprint: 1.44,
    rotation: [0, 0, 0],
    offset: [0, 0, 0],
    preferredAnimationClips: ["Take 001"],
    animationSpeed: 0.82,
    animationLoop: "repeat",
  },
  {
    id: "pulse-frog",
    label: "Pulse frog",
    shortLabel: "Frog",
    description: "A spring-loaded signal scout that hops beside its pilot.",
    modelUrl: SPACEMAN_ANIMATED_PET_URLS.frog,
    sourceNodeName: null,
    icon: "frog",
    rarity: "RARE",
    accent: "#70e39a",
    targetHeight: 0.9,
    targetFootprint: 1.26,
    rotation: [0, Math.PI, 0],
    offset: [0, 0, 0],
    preferredAnimationClips: ["Frog|Jump"],
    animationSpeed: 0.58,
    animationLoop: "repeat",
  },
  {
    id: "ember-element",
    label: "Ember element",
    shortLabel: "Ember",
    description: "A living reactor mote with a stable thirty-second idle cycle.",
    modelUrl: SPACEMAN_ANIMATED_PET_URLS.emberElement,
    sourceNodeName: null,
    icon: "element",
    rarity: "EPIC",
    accent: "#ff8758",
    targetHeight: 1.5,
    targetFootprint: 1.38,
    rotation: [0, Math.PI, 0],
    offset: [0, 0.04, 0],
    preferredAnimationClips: ["idle"],
    animationSpeed: 0.76,
    animationLoop: "repeat",
  },
  {
    id: "orbit-pou",
    label: "Orbit pou",
    shortLabel: "Pou",
    description: "A cheerful low-gravity buddy with a soft breathing idle.",
    modelUrl: SPACEMAN_ANIMATED_PET_URLS.pou,
    sourceNodeName: null,
    icon: "pou",
    rarity: "RARE",
    accent: "#ca8cff",
    targetHeight: 1.36,
    targetFootprint: 1.2,
    rotation: [0, Math.PI, 0],
    offset: [0, 0, 0],
    preferredAnimationClips: ["idle"],
    animationSpeed: 0.9,
    animationLoop: "repeat",
  },
  {
    id: "sky-wyvern",
    label: "Sky wyvern",
    shortLabel: "Wyvern",
    description: "A winged formation guardian holding a calm standing pose.",
    modelUrl: SPACEMAN_ANIMATED_PET_URLS.wyvern,
    sourceNodeName: null,
    icon: "wyvern",
    rarity: "LEGENDARY",
    accent: "#6edcff",
    targetHeight: 1.4,
    targetFootprint: 1.98,
    rotation: [0, -Math.PI / 4, 0],
    offset: [0, 0.03, 0],
    preferredAnimationClips: ["Standing.new", "Standing"],
    animationSpeed: 0.84,
    animationLoop: "repeat",
  },
  {
    id: "nova-sprite",
    label: "Nova sprite",
    shortLabel: "Nova",
    description: "A bright anomaly scout that hovers, scans, and pulses in place.",
    modelUrl: SPACEMAN_PET_PACK_URL,
    sourceNodeName: "1_0",
    icon: "sprite",
    rarity: "COMMON",
    accent: "#a77cff",
    targetHeight: 1.62,
    targetFootprint: 1.48,
    rotation: [0, Math.PI / 2, 0],
    offset: [0, 0, 0],
    proceduralIdle: "sprite-hover",
  },
  {
    id: "ruby-trunk",
    label: "Ruby trunk",
    shortLabel: "Ruby",
    description: "A compact elephant companion with a grounded sway and happy trunk salute.",
    modelUrl: SPACEMAN_PET_PACK_URL,
    sourceNodeName: "2_1",
    icon: "elephant",
    rarity: "RARE",
    accent: "#ff6474",
    targetHeight: 1.55,
    targetFootprint: 1.46,
    rotation: [0, Math.PI / 2, 0],
    offset: [0, 0, 0],
    proceduralIdle: "elephant-sway",
  },
  {
    id: "ion-cub",
    label: "Ion cub",
    shortLabel: "Ion",
    description: "A curious trail finder that listens, leans, and watches its pilot.",
    modelUrl: SPACEMAN_PET_PACK_URL,
    sourceNodeName: "3_2",
    icon: "cub",
    rarity: "RARE",
    accent: "#4ac8ff",
    targetHeight: 1.58,
    targetFootprint: 1.46,
    rotation: [0, Math.PI / 2, 0],
    offset: [0, 0, 0],
    proceduralIdle: "cub-curious",
  },
  {
    id: "ember-drake",
    label: "Ember drake",
    shortLabel: "Ember",
    description: "A winged guardian with a layered hover, wingbeat, and banking idle.",
    modelUrl: SPACEMAN_PET_PACK_URL,
    sourceNodeName: "4_3",
    icon: "dragon",
    rarity: "EPIC",
    accent: "#ffad57",
    targetHeight: 1.72,
    targetFootprint: 1.62,
    rotation: [0, Math.PI / 2, 0],
    offset: [0, 0, 0],
    proceduralIdle: "drake-flight",
  },
] as const satisfies readonly SpacemanPetOption[];

export const getSpacemanPetOption = (
  petId: SpacemanPetId
): SpacemanPetOption => {
  return (
    SPACEMAN_PET_OPTIONS.find((option) => option.id === petId) ??
    SPACEMAN_PET_OPTIONS[0]
  );
};
