/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\asteroid.glb -t -T -o src\\components\\Asteroid.tsx 
Files: public\\models\\asteroid.glb [2.81MB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\asteroid-transformed.glb [480.46KB] (83%)
Author: dianmozokov (https://sketchfab.com/dianmozokov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-environment-prop-rock-458bc46ae1bd41f984f3c5f2edd5f77a
Title: Game Environment Prop: Rock
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    Rock_LowPoly_Rock_LowPoly_0: THREE.Mesh
  }
  materials: {
    Rock_LowPoly: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Asteroid(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/asteroid_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_LowPoly_Rock_LowPoly_0.geometry} material={materials.Rock_LowPoly} />
    </group>
  )
}

useGLTF.preload('/models/asteroid_optimized.glb')
