/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\planet_1.glb -t -T -o src\\components\\Planet1.tsx 
Files: public\\models\\planet_1.glb [252.86KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\planet_1-transformed.glb [18.4KB] (93%)
Author: Gooba (https://sketchfab.com/wilsontaylor2299)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-06276d7a8f2044458a363c2ffa2d4620
Title: Planet
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = {
  nodes: {
    pPlatonic1_lambert1_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Planet1(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/planet_1_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pPlatonic1_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/models/planet_1_optimized.glb')
