/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\planet_5.glb -t -T -o src\\components\\Planet5.tsx 
Files: public\\models\\planet_5.glb [64.32KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\planet_5-transformed.glb [48.08KB] (25%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-186-f-81a4b533cb2e426d85a17a3793a9420e
Title: Pixel Planet Kepler-186-f
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export function Planet5(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/planet_5_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/planet_5_optimized.glb')
