/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\planet_2.glb -t -T -o src\\components\\Planet2.tsx 
Files: public\\models\\planet_2.glb [71.94KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\planet_2-transformed.glb [42.52KB] (41%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-7b-c3f70609c3e64ae4b351f6de01a74cd0
Title: Pixel Planet Kepler-7b
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export function Planet2(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/planet_2_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/planet_2_optimized.glb')
