/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\planet_3.glb -t -T -o src\\components\\Planet3.tsx 
Files: public\\models\\planet_3.glb [62.08KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\planet_3-transformed.glb [39.44KB] (36%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-hd-40307-g-0e9bb5680cf44352968f499786d80e63
Title: Pixel Planet HD-40307-g
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export function Planet3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/planet_3_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/planet_3_optimized.glb')
