/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\planet_6.glb -t -T -o src\\components\\Planet6.tsx 
Files: public\\models\\planet_6.glb [66.63KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\planet_6-transformed.glb [43.74KB] (34%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-trappist-1-e-a8bc914b11a54879971e5a3029f5829c
Title: Pixel Planet TRAPPIST-1-e
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshBasicMaterial
  }
  animations: any[]
}

export function Planet6(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/planet_6_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/planet_6_optimized.glb')
