/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\rocket_ship.glb -t -T -o src\\components\\RocketShip.tsx 
Files: public\\models\\rocket_ship.glb [51.85KB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\rocket_ship-transformed.glb [6.21KB] (88%)
Author: Billy Jackman (https://sketchfab.com/billyjackman3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-ship-low-poly-96858de4225f42048c88be630697f9cb
Title: Rocket Ship - Low Poly
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = {
  nodes: {
    ['Rocket_Ship_01_Material_#28_0']: THREE.Mesh
    ['Rocket_Ship_01_Material_#30_0']: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function RocketShip(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/rocket_ship_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Rocket_Ship_01_Material_#28_0'].geometry} material={materials.PaletteMaterial001} position={[0.421, 0.421, -0.033]} rotation={[-Math.PI / 2, Math.PI / 4, 0]} scale={0.01} />
      <mesh geometry={nodes['Rocket_Ship_01_Material_#30_0'].geometry} material={materials.PaletteMaterial002} position={[0.421, 0.421, -0.033]} rotation={[-Math.PI / 2, Math.PI / 4, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/rocket_ship_optimized.glb')
