/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ..\\public\\models\\spaceman_white.glb -t -T -o src\\components\\SpacemanWhite.tsx 
Files: ..\\public\\models\\spaceman_white.glb [4.76MB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\spaceman_white-transformed.glb [320.38KB] (93%)
Author: besturkan (https://sketchfab.com/besturkan)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/spaceman-d78d834779be41c5b62fa6f03dee3398
Title: Spaceman
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    Cube011_Material001_0: THREE.Mesh
    Cube012_Material002_0: THREE.Mesh
    Cube020_Material005_0: THREE.Mesh
    Cylinder002_Material003_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
  }
  animations: any[]
}

// NOTE: Mouse following logic removed for debugging
export function SpacemanWhite(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/spaceman_white_optimized.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube011_Material001_0.geometry} 
        material={materials.PaletteMaterial001} 
        position={[-0.405, 2.52, -0.44]} 
        rotation={[-Math.PI, -0.972, -Math.PI]} 
        scale={0.015} 
      />
      <mesh 
        geometry={nodes.Cube012_Material002_0.geometry} 
        material={materials.PaletteMaterial002} 
        position={[-0.428, 2.52, -0.41]} 
        rotation={[-Math.PI, -0.972, -Math.PI]} 
        scale={[0.018, 0.0165, 0.018]} 
      />
      <mesh 
        geometry={nodes.Cube020_Material005_0.geometry} 
        material={materials.PaletteMaterial003} 
        position={[0.238, 1.097, -1.392]} 
        rotation={[-Math.PI, -0.972, -Math.PI]} 
        scale={[0.006, 0.012, 0.0135]} 
      />
      <mesh 
        geometry={nodes.Cylinder002_Material003_0.geometry} 
        material={materials.PaletteMaterial004} 
        position={[0.627, 1.9, -0.927]} 
        rotation={[-Math.PI, -0.972, -Math.PI]} 
        scale={0.015} 
      />
    </group>
  )
}

useGLTF.preload('/models/spaceman_white_optimized.glb')
