/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\\models\\space_galaxy.glb -t -T -o src\\components\\SpaceGalaxy.tsx 
Files: public\\models\\space_galaxy.glb [1.4MB] > C:\Users\Administrator\Documents\test2\space-academy-app\src\components\space_galaxy-transformed.glb [1.4MB] (0%)
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    Object_2: THREE.Points
  }
  materials: {
    ['Scene_-_Root']: THREE.PointsMaterial
  }
  animations: any[]
}

export function SpaceGalaxy(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/space_galaxy_optimized.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <points geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('/models/space_galaxy_optimized.glb')
